<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<project name="libroJava" default="generaLibro" basedir=".">
	<property environment="env"/>
	<!-- il gioco qui sotto funziona perhé le propietà di and sono immutabili
	http://ant.apache.org/manual/Tasks/property.html -->
	<property name="env.BOOK_TARGET_FOLDER" value="${basedir}/compilati/"/>

    <taskdef name="compilaLibro" classname="it.aspix.ebook.AntTask" >
		<classpath>
			<pathelement location="lib/libro-compilatore.jar"/>
		</classpath>
    </taskdef>

	<target name="generaLibro" description="compila il libro">
		<echo>output in ${env.BOOK_TARGET_FOLDER}</echo>
    	<compilaLibro 
    		sorgenti="${basedir}/sorgenti/" 
    		compilati="${env.BOOK_TARGET_FOLDER}"
    		quiet="true"
		    limiteDataChangelog="2020-08-01"
    	/>            
    </target>
</project>